### ISSUE TITLE
it keeps saying “ModuleNotFoundError: No module named 'view.clean_data'”

### ISSUE THREAD

**Issue by lqrqw13** [hsuanchi/crawler_shopee_public#1]
Hi there, first of all, thanks for your scripts. I already install the all requirements by "pip3 install -r requirement.txt". But it keeps giving me this err info “ModuleNotFoundError: No module named 'view.clean_data'”

**Comment by ckshdion** [comment]
I got the same problem

**Comment by hsuanchi** [comment]
Hello, thanks for asking, fix it :)
