### ISSUE TITLE
"https://shopee.tw/api/v2/item/get?" 回傳的內容非最新資訊。

### ISSUE THREAD

**Issue by dzjones26** [hsuanchi/crawler_shopee_public#3]
Hi 您好：
感謝您提供這個project幫助我了解蝦皮。我在使用上有一些狀況，也許是操作問題，因此想直接請教，如果有誤還請指正。我以" https://shopee.tw/api/v2/item/get? " 取得之內容似乎與蝦皮公開資訊不同，由devtool查看，蝦皮是由v4 fetch而非v2，想請教作者v2是否已非最新api？謝謝。

![截圖 2021-10-11 下午11 22 31](https://user-images.githubusercontent.com/37979164/136815754-75c2078b-bbe9-4161-9446-1730c5bc6ee1.png)

**Comment by hsuanchi** [comment]
嗨嗨，看起來是 API 版本不同，你也可以更新到 v4 版本使用 :)

**Comment by dzjones26** [comment]
了解了，感謝回覆。另外再請教一下「每日銷量」的值是sold還是histrical_sold呢？一直對不太起來。謝謝。

**Comment by hsuanchi** [comment]
嗨嗨，我之前是抓 v2 的 sold 喲
```
items_type[i]['sold']
```
