### ISSUE TITLE
請問這個專案能在哪個版本下執行?

### ISSUE THREAD

**Issue by jiamingla** [hsuanchi/crawler_shopee_public#4]
我在裝crawler_shopee_public\requirement.txt時有點卡關
用venv or pipenv都不能順利裝上
我猜問題在我的環境是Python 3.9?

**Comment by hsuanchi** [comment]
Hi, 

Python 3.7+ 都可以，試試 upgrade 你的 pip，再重新安裝

```
$ pip3 install pip --upgrade

$ pip3 install -r requirements.txt 
```
