### ISSUE TITLE
你好 马来西亚虾皮可以使用？ 

### ISSUE THREAD

**Issue by jinghan713** [hsuanchi/crawler_shopee_public#5]
由于马来西亚地区的shop id 是string 所以可以适应string 来寻找商店？

**Comment by hsuanchi** [comment]
Hello @jinghan713 
Thanks for the issues, I resolved it in commit [#c8a4dc317f26098c16888d1ef7352bdd4f29148a](https://github.com/hsuanchi/crawler_shopee_public/tree/c8a4dc317f26098c16888d1ef7352bdd4f29148a) by replacing the `shop_id` with `shop_name`.
