### ISSUE TITLE
執行main.py無法抓取

### ISSUE THREAD

**Issue by alvinlulu** [hsuanchi/crawler_shopee_public#7]
您好!我執行main.py後, 屏幕顯示
google.auth.exceptions.DefaultCredentialsError: File /tele_bot/crawler_shopee_public-master/config/crawler_bigquery.json was not found.
確認dev log 有看到 object no attribute 
Exception: 'DevelopmentConfig' object has no attribute 'PROXY_URL'

無法正確執行
這有什麼solution嗎?

**Comment by hsuanchi** [comment]
Hello @alvinlulu,

這是給如果有要加上 IP Pool 的朋友，目前已經新增了 default `PROXY_URL: str = None` 參數，如果執行上還是有遇到問題再和我說！
