### ISSUE TITLE
can not catch products info

### ISSUE THREAD

**Issue by alvinlulu** [hsuanchi/crawler_shopee_public#8]
hi hsuanchi

今天抓取蝦皮資訊時，發現pdp_detail裡面的資料是空值，是否api有改版了

**Comment by alvinlulu** [comment]
the problem is the header error, resolve this.

**Comment by alvinlulu** [comment]
Replace your header.

**Comment by ZhengSang** [comment]
Hello, means replace the 'User-Agent' section in the api_v4_product_details.py and api_v4_shop_details.py files?

**Comment by wilsonlu207** [comment]
> the problem is the header error, resolve this.

Hi @alvinlulu , could you explain in detail how to solve empty data in a spreadsheet?  thank you very much .
